@startuml
'https://plantuml.com/sequence-diagram

 Employees ...|>  Employee : contains list of

Class Employees {

-ArrayList<Person> list;
+addPerson();
+getPerson();
+generateOutput();
+generateSpacing();
}

Class Employee{
-String firstName;
-String lastName;
-int salary;

+getFirstName();
+setFirstName();
+getLastName();
+setLastName();
+getSalary();
+setSalary();
}

@enduml