@startuml
'https://plantuml.com/sequence-diagram
Class SearchWord {
-String original
-String replacement

+setOriginal()
+getOriginal()
+setReplacement()
+getReplacement()
}
Class Phrase extends SearchWord{
-String phrase
-int instancesOfWord

+setPhrase()
+getPhrase()
+incrementInstancesOf()
+replaceWord()
}

@enduml